bigdatagenomics/avocado

avocado-cli/pom.xml
avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/Avocado.scala
avocado-core/pom.xml
avocado-core/src/main/scala/org/bdgenomics/avocado/Timers.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/discovery/Explore.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/discovery/ReadExplorer.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/BiallelicGenotyper.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/CallGenotypes.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/ExternalGenotyper.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/stats/AvocadoConfigAndStats.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/AvocadoFunSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/algorithms/debrujin/KmerGraphSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/discovery/ReadExplorerSuite.scala
pom.xml

Resolves #130. Adds timers and does various other upgrading things.

[avocado-130] Upgrade to latest ADAM/Spark and add timers to avocado.

---

avocado-core/pom.xml
avocado-core/src/main/scala/org/bdgenomics/avocado/algorithms/em/EMforAlleles.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/algorithms/math/LogBinomial.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/algorithms/math/LogUtils.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/BiallelicGenotyper.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/algorithms/em/EMforAllelesSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/algorithms/math/LogBinomialSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/algorithms/math/LogUtilsSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/algorithms/math/MathTestUtils.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/genotyping/BiallelicGenotyperSuite.scala
avocado-sample-configs/basic.properties
docs/source/03_architecture.md
docs/source/05_algorithms.md
docs/template.tex
pom.xml

Resolves #122. Reintegrated EM algorithm for estimating frequency of reference allele, which is used as a prior when genotyping.

[avocado-122] Tested and reintegrated EM algorithm.

---

avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/Avocado.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/ExternalGenotyper.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/input/AlignedReadsInputStage.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/input/SnapInputStage.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/preprocessing/MarkDuplicates.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/preprocessing/RealignIndels.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/preprocessing/RecalibrateBaseQualities.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/preprocessing/SortReads.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/stats/AvocadoConfigAndStats.scala

[avocado-138] Remove context references.

---

avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/BiallelicGenotyper.scala
avocado-sample-configs/basic.properties
pom.xml

Resolves #140. Adds a few other small fixes.

[avocado-140] Forces instrumentation in bialleic genotyper.

---

pom.xml

[avocado-146] Upgraded to ADAM 0.16.1-SNAPSHOT.

---

avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/annotators/Annotator.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/genotyping/annotators/VariantCallingAnnotatorSuite.scala

Make rank sum annotation optional so that it isn't applied if we do not have alt/ref observations.

---

pom.xml

[avocado-179] Move to ADAM 0.17.1 release.

---

avocado-core/src/main/scala/org/bdgenomics/avocado/input/AlignedReadsInputStage.scala

Cherrypicking https://github.com/fnothaft/avocado/commit/a7e182def1a01e482f49b13e7f4042d1b5c1b601 from #127.

[avocado-162] Only project selected fields on load.

---

avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/BiallelicGenotyper.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/util/TreeRegionJoin.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/util/TreeRegionJoinSuite.scala

[AVOCADO-202] Pulled back in TreeRegionJoin.

---

pom.xml
scripts/jenkins-test

[AVOCADO-211] Push coverage reports to Coveralls.

---

avocado-core/src/main/scala/org/bdgenomics/avocado/serialization/AvocadoKryoRegistrator.scala
bin/avocado-submit

Resolves #209. Pulls kryo registration back from c6aaaf5.

[AVOCADO-209] Pull AvocadoKryoRegistrator back in.

---

avocado-core/pom.xml

[AVOCADO-218] Remove incremental compile mode.

---

avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/BiallelicGenotyper.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/util/HardFilterGenotypes.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/genotyping/BiallelicGenotyperSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/util/HardFilterGenotypesSuite.scala

[AVOCADO-220] Add allelic fraction hard filter.

---

avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/Reassemble.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/util/PrefilterReads.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/genotyping/DiscoverVariantsSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/realigner/RealignerSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/util/PrefilterReadsSuite.scala
pom.xml

[AVOCADO-226] Upgrade to ADAM 0.22.0

---

avocado-cli/pom.xml
pom.xml

[AVOCADO-236] Rename artifacts in POM dependencies.

---

avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/AvocadoMain.scala
avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/TrioGenotyper.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/TrioCaller.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/util/HardFilterGenotypes.scala
avocado-core/src/test/resources/trio.1_837214.phased.vcf
avocado-core/src/test/resources/trio.1_837214.vcf
avocado-core/src/test/scala/org/bdgenomics/avocado/genotyping/TrioCallerSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/util/HardFilterGenotypesSuite.scala
bin/avocado-submit

[AVOCADO-235] Add trio caller.

---

avocado-core/pom.xml
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/BiallelicGenotyper.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/DiscoverVariants.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/DiscoveredVariant.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/Observer.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/ScoredObservation.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/SummarizedObservation.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/genotyping/BiallelicGenotyperSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/genotyping/DiscoverVariantsSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/genotyping/DiscoveredVariantSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/genotyping/ObserverSuite.scala
pom.xml

Move genotyping unit over to Spark SQL

---

avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/BiallelicGenotyper.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/util/HardFilterGenotypes.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/util/RewriteHets.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/util/RewriteHetsSuite.scala

[AVOCADO-222] Add code to process high allelic fraction het calls.

---

avocado-cli/pom.xml
avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/BiallelicGenotyper.scala
avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/DiscoverVariants.scala
avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/Reassemble.scala
avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/TrioGenotyper.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/BiallelicGenotyper.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/DiscoverVariants.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/util/HardFilterGenotypes.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/util/PrefilterReads.scala
avocado-core/src/test/resources/trio.1_837214.phased.vcf
avocado-core/src/test/scala/org/bdgenomics/avocado/genotyping/BiallelicGenotyperSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/genotyping/DiscoverVariantsSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/genotyping/TrioCallerSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/realigner/RealignerSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/util/PrefilterReadsSuite.scala
pom.xml

[AVOCADO-252] Move to ADAM 0.23.0.

---

avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/AvocadoMain.scala
avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/MergeDiscovered.scala
avocado-cli/src/test/resources/NA12878.1_907170_A2C.vcf
avocado-cli/src/test/resources/NA12878.1_907170_AG2A.vcf
avocado-cli/src/test/scala/org/bdgenomics/avocado/cli/MergeDiscoveredSuite.scala

[AVOCADO-264] Add CLI for merging discovered variants across multiple samples.

---

avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/BiallelicGenotyper.scala
avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/Jointer.scala
avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/TrioGenotyper.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/BiallelicGenotyper.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/DiscoveredVariant.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/JointAnnotatorCaller.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/SquareOffReferenceModel.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/util/HardFilterGenotypes.scala
avocado-core/src/test/resources/gvcf_multiallelic.g.vcf
avocado-core/src/test/scala/org/bdgenomics/avocado/genotyping/BiallelicGenotyperSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/genotyping/DiscoverVariantsSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/genotyping/SquareOffReferenceModelSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/util/HardFilterGenotypesSuite.scala

[AVOCADO-249] Support BP resolution gVCF output.

---

avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/BiallelicGenotyper.scala
avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/Jointer.scala
avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/TrioGenotyper.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/BiallelicGenotyper.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/DiscoveredVariant.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/JointAnnotatorCaller.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/Observer.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/ScoredObservation.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/SquareOffReferenceModel.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/SummarizedObservation.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/models/CopyNumberMap.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/models/Observation.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/util/HardFilterGenotypes.scala
avocado-core/src/main/scala/org/bdgenomics/avocado/util/RewriteHets.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/genotyping/BiallelicGenotyperSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/genotyping/ObserverSuite.scala
avocado-core/src/test/scala/org/bdgenomics/avocado/models/CopyNumberMapSuite.scala

[AVOCADO-272] Support variable copy number when genotyping.

---

avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/BiallelicGenotyper.scala
avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/TrioGenotyper.scala
docs/workflows/single-sample.rst

[AVOCADO-285] Fix bad argument names/argument name documentation.

---

avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/BiallelicGenotyper.scala

[AVOCADO-289] Reduce the amount of memory consumed by observations.

---

avocado-cli/pom.xml
avocado-core/pom.xml
avocado-core/src/main/scala/org/bdgenomics/avocado/genotyping/SquareOffReferenceModel.scala
avocado-distribution/pom.xml
pom.xml
scripts/jenkins-test

[AVOCADO-299] Bump to ADAM 0.24.0.

---

docs/conf.py
docs/requirements.txt

[AVOCADO-298] Clean up Sphinx documentation build.

---

avocado-cli/src/main/scala/org/bdgenomics/avocado/cli/BiallelicGenotyper.scala

[AVOCADO-291] Add more helpful error message when read groups are missing
